### ISSUE TITLE
no response / how to pair ?

### ISSUE THREAD

**Issue by pjchx** [fbeek/pimatic-maxcul#14] opened 2016-10-28 00:22 UTC
Hello,
I have a rpi2+CUL v3 + MaxWandThermostat.

When trying to command the Thermostat from Pimatic I get error about No response. (see below)
How do I pair the CUL with the Thermostat in Pimatic ?  I knew how to do it in FHEM, but not sure about the Pimatic....
thanks for response
Pjchx

00:12:19.112 [pimatic] Starting pimatic version 0.9.34
00:12:19.589 [pimatic] Invalid config: Missing property "allowedOrigin" in /settings/cors
00:12:23.548 [pimatic, ppm] 2.15.6
00:12:23.616 [pimatic] Loading plugin: "pimatic-cron" (0.8.8)
00:12:24.420 [pimatic] Loading plugin: "pimatic-mobile-frontend" (0.9.11)
00:12:25.550 [pimatic] Loading plugin: "pimatic-unipi-evok" (0.2.9)
00:12:26.659 [pimatic] Loading plugin: "pimatic-maxcul" (0.9.2)
00:12:26.969 [pimatic-cron] the time is: Fri Oct 28 2016 00:12:26 GMT+0000 (UTC)
00:12:28.063 [pimatic-maxcul] using serial device /dev/ttyACM0@9600
00:12:28.300 [pimatic-maxcul] serialPort /dev/ttyACM0 is open!
00:12:28.652 [pimatic] New device "Thermostat 1"...
00:12:28.837 [pimatic] New device "UniPi Relay 1"...
00:12:28.903 [pimatic] New device "UniPi Relay 2"...
00:12:28.955 [pimatic] New device "UniPi Relay 3"...
00:12:29.008 [pimatic] New device "UniPi Relay 4"...
00:12:29.058 [pimatic] New device "UniPi Relay 5"...
00:12:29.112 [pimatic] New device "UniPi Relay 6"...
00:12:29.167 [pimatic] New device "UniPi Relay 7"...
00:12:29.213 [pimatic] New device "UniPi Relay 8"...
00:12:29.289 [pimatic] New device "UniPi Temperature"...
00:12:29.418 [pimatic] New device "UniPi Analog Output 1"...
00:12:29.494 [pimatic] New device "UniPi Analog Input 1"...
00:12:29.550 [pimatic] New device "UniPi Analog Input 2"...
00:12:29.622 [pimatic] New device "UniPi Digital Input 1"...
00:12:29.685 [pimatic] New device "UniPi Digital Input 2"...
00:12:29.727 [pimatic] New device "UniPi Digital Input 3"...
00:12:29.764 [pimatic] New device "UniPi Digital Input 4"...
00:12:29.804 [pimatic] New device "UniPi Digital Input 5"...
00:12:29.843 [pimatic] New device "UniPi Digital Input 6"...
00:12:29.890 [pimatic] New device "UniPi Digital Input 7"...
00:12:29.929 [pimatic] New device "UniPi Digital Input 8"...
00:12:30.843 [pimatic-maxcul] CUL FW Version: V 1.66 CUL868
00:12:30.982 [pimatic-unipi-evok] [UniPiUpdateManager] unable to get device status, exception caught:  Error: Internal Server Error (500)
00:12:31.674 [pimatic-mobile-frontend] packing static assets
00:12:33.686 [pimatic-mobile-frontend] packing static assets finished
00:12:33.701 [pimatic-mobile-frontend] rendering html
00:12:48.508 [pimatic-mobile-frontend] rendering html finished
00:12:48.814 [pimatic] Listening for HTTP-request on port 81...
00:13:01.918 [pimatic-maxcul] transfer config to device 0d0cf6
00:13:08.872 [pimatic-maxcul] Paket 0b0100401234560d0cf60027 send but no response!
00:13:20.890 [pimatic-maxcul] Paket 110100111234560d0cf60028223d0907090c send but no response!
Unhandled rejection Paket 110100111234560d0cf60028223d0907090c send but no response!

**Comment by fbeek** [comment] 2016-10-28 06:13
Hello,

do you mean the WallThermostat with Display or the Heatingthermostat?

 As you can see in the Readme the WallThermostat and the WallButton where currently not supportet. I doesn't own one off this devices so i cant implement the function in the moment.

Normally the Pairing is simple. You just activate it in de plugin config as said in the readme, restart pimatic, Push the pairbutton on the device. From the debbug you then get the device id for the configuration. 

At the moment you need to setup the config by yourself, because the auto discover from Pimatic is not supportet yet.

Never the less the last message from your system looks strange. I will the check the code later if its because of the Wallthermostat or a bug.

Regards
fbeek

**Comment by pjchx** [comment] 2016-10-28 08:19
Hello, thanks for a quick response.

I mean  this WallThermostat
http://www.elv.de/max-wandthermostat-arr-bausatz-1.html

Also I try to implement use of this button:
http://www.elv.de/elv-max-wandtaster-eco-arr-bausatz.html

If these are not supported now -  is there a chance that it will work at
all (for example only some features) ?

Also I can participate on implementing these new units - but I am quite new
to this area - is there any good documentation where I can start learning
about it?

Pjchx

**Comment by fbeek** [comment] 2016-10-28 09:19
Unfortunately these two devices are not supported at the moment.

The problem is not the implementation on node.js / Pimatic.
Every MAX! Device supports a special set of instructions and every command in the network has a special payload encoding. Without a Device a can't reverse engineer the payload protocol.

I can reverse engineer some basic from the FHEM software but without a test device it is a pain to develop. 

There is no documentation about the protocol you need to reverse engineer everything from scratch. It took me 7 Month (beneath my work :-)) to understand it.

How are your CoffeeScript / JS Skills?

**Comment by fbeek** [comment] 2016-11-08 09:08
I close this because of missing feedback.

**Closed as completed** 2016-11-08 09:08 UTC
Labels: question, in progress
