### ISSUE TITLE
Pairing is disabled 

### ISSUE THREAD

**Issue by Jeason1598** [fbeek/pimatic-maxcul#38] opened 2018-03-30 19:31 UTC
I have some troubles with the Maxcul - Plugin, i can discover a new Device but it's not really working. It cannot send Data to the Max!Heating Thermostat. 
When i press the Boost - Button, it writes to me that pairing is disabled 
![maxcul](https://user-images.githubusercontent.com/37940582/38150966-a6157da6-3461-11e8-8fed-f92e35daf36b.PNG)
Device looks like it is not loaded 
![maxcul2](https://user-images.githubusercontent.com/37940582/38150992-b7609ea6-3461-11e8-9236-9a60f1ac16ce.PNG)

Config of maxcul:

![maxcul3](https://user-images.githubusercontent.com/37940582/38150995-bd8cd7f4-3461-11e8-8346-149013d51e89.PNG)

Hope someone can help me, thanks.

**Comment by fbeek** [comment] 2018-03-30 21:23
Hello,
I have tested the pair mode a few minutes ago and it works as expected and written in the readme.
The message in your log says that the device is trying to pair with Pimatic but device discovery is not active. Have you saved the discovered devices? I mean opened it and saved the settings? The Discovery mode of Pimatic shows the devices only but does nothing more.

As this is not a bug, but a usage problem i close this issue.
Please use the Pimatic [Forum](https://forum.pimatic.org/) for usage help in the future.

**Closed as completed by fbeek** 2018-03-30 21:23 UTC
Labels: can not recreate error, usage problem on user side
