### ISSUE TITLE
not conecting right in pimatic 0.9

### ISSUE THREAD

**Issue by danielboe** [fbeek/pimatic-maxcul#11] opened 2016-10-17 21:03 UTC
i get the following debug on startup:
21:00:39.724 [pimatic-maxcul] info: Timeout on CUL connect, cul is available but not responding
21:00:40.092 [pimatic-maxcul] info: CUL FW Version: V 1.66 nanoCUL868
after that I can´t receive any debug if I pair devices. Also after a while I get 
20:58:03.950 [pimatic-maxcul] info: CUL FW Version: LOVF

hope this helps for the 0.9 release.

thanks

Daniel

**Comment by fbeek** [comment] 2016-10-18 13:53
Hello Daniel,

which version of the plugin have you installed ?
The latest 0.9x?
What machine are you using(RPi 1,2,3 etc.)

I have changed the timeouts for 0.9 because of an race condition while starting pimatic.
This is only a workaround but it worked for me.

Have you added the devices to the configuration after pairing and restarted pimatic ? At the moment the plugin does not support autodiscover.

Regards
Flo

**Comment by fbeek** [comment] 2016-10-24 15:00
With the latest version i cannot reproduce the error and so i will close this issue.

**Closed as completed by fbeek** 2016-10-24 15:00 UTC
Labels: question
