### ISSUE TITLE
Max! Device communication problems since update to 1.1.0

### ISSUE THREAD

**Issue by eq06belu** [fbeek/pimatic-maxcul#43] opened 2019-07-18 09:25 UTC
Communication with Max! devices (wall thermostats and window contacts) does not work (stable) anymore. I have this issue since I have updated to version 1.1.0.
At the beginning, I was able to solve the problem temporarily by manually installing version 1.0.7 but since I have also updated to the latest pimatic version (0.9.50) this does not work anymore.
I am using a pre-build nanoCUL with FTDI and CC1101. I have tried several different firmware versions and settings without any success. At the moment (of log file generation) I have flashed version r568.

Here you can find parts of my config (Maxcul plugin and device config):
[config.txt](https://github.com/fbeek/pimatic-maxcul/files/3405798/config.txt)

Here I have attached the daemon-log from start (after a while I tried to change a set temperature from the pimatic GUI):
[pimatic-daemon.log](https://github.com/fbeek/pimatic-maxcul/files/3405663/pimatic-daemon.log)

**Comment by fbeek** [comment] 2019-07-18 10:01
Hello, 

thank you for your detailed response on this error. In my live system and my testing system i cannot reproduce any error at the moment. I will try to decode your messages by hand in the evening and will check the responses. The good news is that it is not an isseue with the usb serial communication. 

I will check this and come back to you with the result.

Regards
fbeek

**Comment by fbeek** [comment] 2019-07-18 11:57
Hey,

i decoded you messages from the log with my test script and these where fine.
One thing that can be a problem is the missing CUL Version information in your log.

Can you please flash your cul with Version 1.61 and give it another try? There where many changes in the firmware that can possibly make problems.

Regards
fbeek

**Comment by eq06belu** [comment] 2019-07-23 14:51
Hello,

I have flashed the last revision of 1.61 of culfw (r469 from sourceforge) to my nanoCUL.
Unfortunately, I cannot observe an improvement in behavior.

I run out of ideas in how to get it working again.

Can you help me going back to version 1.0.7 of pimatic-maxcul?
Whenever I try to do so with
`sudo npm install pimatic-maxcul@1.0.7 --unsafe-perm`
, I get a lot of errors during installation. Afterwards, when restarting, pimatic is recompiled and it automatically installs pimatic-maxcul with the latest version (1.1.0).
It seems like I am doing something wrong.

Of course it would be my preferred solution to make it working with the latest version, but knowing that winter comes again, I would really like to have a kind of fallback solution.

Many thanks in advance for your support!!!

BR,
Lukas

**Comment by fbeek** [comment] 2019-07-23 16:55
Hello Lukas,

ok that is not good but if we work together we will find a solution before the next winter :-)

Please keep in mind that Version 1.0.7 will not work with a node version higher as 4.6.x and 1.1.0 will not work under node version 10.16.x.

In emergency it is the easiest way to make a fresh pimatic installation on the old node version and after first start delete the maxcul folder in node-modules and install an older tag from github. This is the way i test new versions.

But this should be the last resort. I think we should try to find the differences of your setup an mine.

I use Raspian jessie as production system, node v10.16 with latest pimatic and maxcul.
On my cul I use firmware v 1.61 and this system works without any errors.

I do not use bounded devices (Wall Thermostat) all devices are stand alone and combined by pimatic.

One thing that i found in your logs is that you did not set a base id (homebaseAddress) so the devices use 123456 as default. But some of your messages contain 000000 as base address. I think these where not paired correctly with maxcul. I have added a decode script to the repo, its plain stupid and you have to install the modules via npm by hand because i had no time to make package.json. With this you can decode the message from the log.

The main Problem of your setup is that it recognizes all messages but not the ACK NAK messages.
I n your log i can see that there is no corresponding message to [pimatic-maxcul] debug: check CUL Firmware version. This means that maxcul doesn`t get the Firmware message from the CUL and so it is not clear if it enables the max mode of the cul device.

I think this is the main problem. But here it works fine.
Have you fhem running in background?

BR
Flo

**Comment by eq06belu** [comment] 2019-07-23 19:21
Hello,

many thanks for your fast replies!

My node.js version is also 10.16.0.
So at least now I got the reason why I cannot "downgrade". Thanks for the hint! 

I am using raspbian 9.9 (stretch) . Maybe this makes the difference? 

With one or two of my wall thermostats, I have tried to make a hard reset and pair them again (to solve this problem after update). This did not work. I think, those have the "000000" as homebaseAdress.
No, I have no fhem installed. The following services are running:
pi@raspberrypi:~ $ sudo service --status-all
 [ - ]  alsa-utils
 [ + ]  avahi-daemon
 [ + ]  bluetooth
 [ - ]  console-setup.sh
 [ + ]  cron
 [ + ]  dbus
 [ + ]  ddclient
 [ + ]  dhcpcd
 [ + ]  dphys-swapfile
 [ + ]  fake-hwclock
 [ - ]  hwclock.sh
 [ - ]  keyboard-setup.sh
 [ + ]  kmod
 [ - ]  lightdm
 [ + ]  networking
 [ - ]  nfs-common
 [ + ]  nmbd
 [ - ]  paxctld
 [ + ]  pimatic
 [ - ]  plymouth
 [ - ]  plymouth-log
 [ + ]  procps
 [ + ]  raspi-config
 [ + ]  rpcbind
 [ - ]  rsync
 [ + ]  rsyslog
 [ + ]  samba
 [ - ]  samba-ad-dc
 [ - ]  screen-cleanup
 [ + ]  smbd
 [ + ]  ssh
 [ - ]  sudo
 [ + ]  triggerhappy
 [ + ]  udev
 [ - ]  x11-common
 [ + ]  xrdp

Hope, this helps!

Many thanks again!

BR, Lukas

**Comment by fbeek** [comment] 2019-07-28 17:38
Hello Lukas,

thank you for your reply.
I think Stretch is the Problem.

But at the moment i do not know why, there where some issues with Stretch and the node serial port module.

I am still investigating the problem.
I think until the end of the week a have new informations on  this.

BR, Florian

**Comment by smarthomeagentur** [comment] 2019-08-05 13:19
Here is also a Log from me: https://pastebin.com/TVkjFdPk
The Stick worked with node 4 and before 1.1.0. I think its the same behavior. If more logs are needed please ask!

**Comment by fbeek** [comment] 2019-08-05 13:26
Thank you for your reply.

 Iam still working on this and it looks like a problem in Stretch and the new Node Version.

**Comment by eq06belu** [comment] 2019-08-07 06:58
Hello,

first of all, I want to thank you all for putting so much effort in making this great setup working again!
I have some news from my system:
Some days ago, I tried to make some updates of my raspian system with:
`sudo ap-get update`, `sudo apt-get upgrade` and `sudo apt-get dist-upgrade`.
At the beginning it seemed like nothing has changed, but I saw some updates concerning node-modules been done.
Yesterday, for some reason I was annoyed of the debug messages from the pimatic-maxcul plugin, so I disabled the debug mode and restarted pimatic (with the button in the plugins section).
Basically, I did not expect any improvement, but when I came home, I recognized, that pimatic received the change of a window contact and I was even able to see all measured temperatures of my wall thermostats sice restarting pimatic.
I am not sure, was really the root cause of the improvement (apt-get updates, debug disable, restart,...). I also do not know if this is working stable now. At least it seems to work for the moment and will do further investigations, when I find some time.
Maybe this gives you some useful hints for your "more professionell" investigations...

Best regards,
Schöne Grüße aus Kärnten,
Lukas

**Comment by fbeek** [comment] 2019-08-12 07:57
Hello Lukas,

yes i can confirm this. I have tested it with a fresh installed Raspian and after an Update everything works fine. 

I will close the ticket for now.

Best Regards
Florian

**Comment by eq06belu** [comment] 2019-08-13 07:11
Hello Florian,

I am not sure if this issue should be closed already... (Sorry!)

In my configuration the communication is still not working as soon as I activate debugging.
I also noticed that the communication gets stuck as soon as I try to set some values (e.g. temperature setpoint). So receiving messages seems to work when debugging is disabled but stops working when trying to send messages via the nanoCUL. At least this was the status yesterday.
Today, when I tried to reproduce this behavior, I did not have success: Means the communication did not work at all. Something seems to be unstable. I have no idea what it could be.

Again: Many thanks in advance for your support!

BR,
Lukas

**Comment by treban** [comment] 2019-08-15 15:37
HI Florian, 

i have the same problem. But only sometimes. 
with screen on the usb port directly i always get the cul interface. 

After some restarts of pimatic/plugin the connection works, until i restart.
then after some restart its working again. 

HOST: amd64 plattform
OS: Ubuntu 18.04.3 LTS
Pimatic running as **docker**
pimatic version 0.9.50
Node.js version 10.16.0
OpenSSL version 1.1.1b
pimatic-maxcul 1.1.0
hardware is a nanoV3 with CC1101 868
FIrmware: V 1.26.07 a-culfw Build: private build (unknown) nanoCUL868 (F-Band: 868MHz)
(source https://github.com/heliflieger/a-culfw)
I also tried the  latest original culfw firmware. 

a weird decoder thing:
decoding this message, (which i get with a working plugin)
```
17:02:38.824 [pimatic-maxcul] debug: decoding Message Z0F000460149C8D0000000059002A00E508
17:02:38.825 [pimatic-maxcul] debug: RSSI for Message : -70
17:02:38.828 [pimatic-maxcul] debug: got data from heatingelement 149c8d with payload 59002A00E5
```
is not decodable 
```
var msg = "Z0F000460149C8D0000000059002A00E508\r\n";
RSSI: -70
--> Data after split
[ '0F',
  '00',
  '04',
  '60',
  '149C8D',
  '000000',
  '00',
  '59002A00E508',
  '' ]
Packet Length delivered: 15
Length converted: 33
Raw Packet Length: 35
--> packet length missmatch
```

but this not working message, if the plugin is broken
```
17:09:32.364 [pimatic-maxcul] debug: incoming raw data from CUL: Z0E010202149C8D232323000159002A
17:09:32.364 [pimatic-maxcul] debug: decoding Message Z0E010202149C8D232323000159002A
17:09:32.365 [pimatic-maxcul] debug: RSSI for Message : -53
17:09:32.365 [pimatic-maxcul] debug: packet length missmatch
17:09:32.365 [pimatic-maxcul] debug: message was no valid MAX! paket.
```
is decodable?
```
var msg = "Z0E010202149C8D232323000159002A\r\n";
RSSI: -53
--> Data after split
[ '0E', '01', '02', '02', '149C8D', '232323', '00', '0159002A', '' ]
Packet Length delivered: 14
Length converted: 31
Raw Packet Length: 31
--> packet length ok
MessageCounter: 1
Flag: 2
GroupId: 0
RawType: 02
Source: 149C8D
Dest: 232323
RawPayload: 0159002A
```



**Working**
```
16:43:27.289 [pimatic] info: Loading plugin: "pimatic-maxcul" (1.1.0)
16:43:27.290 [pimatic] debug: debug is true in plugin config, showing debug output for pimatic-maxcul.
16:43:58.817 [pimatic-maxcul] info: using serial device /dev/cube@38400
16:43:59.197 [pimatic-maxcul] info: serialPort /dev/cube is open!
16:43:59.198 [pimatic-maxcul] debug: check CUL Firmware version
16:43:59.208 [pimatic-maxcul] debug: Requested CUL Version...
16:43:59.224 [pimatic-maxcul] debug: incoming raw data from CUL: V 1.26.07 a-culfw Build: private build (unknown) nanoCUL868 (F-Band: 868MHz)
16:43:59.225 [pimatic-maxcul] debug: Got Version String
16:43:59.225 [pimatic-maxcul] info: CUL FW Version: V 1.26.07 a-culfw Build: private build (unknown) nanoCUL868 (F-Band: 868MHz)
16:43:59.225 [pimatic-maxcul] debug: Trigger Resolver on ready
16:43:59.225 [pimatic-maxcul] debug: enable MAX! Mode of the CUL868
16:44:01.752 [pimatic-maxcul] debug: templates loaded
16:44:01.846 [pimatic-maxcul] debug: Send Packet to CUL: 0b010630232323149c8d2010, awaiting drain event
16:44:01.913 [pimatic-maxcul] debug: serial port buffer have been drained
16:44:03.438 [pimatic-maxcul] debug: incoming raw data from CUL: Z0E010202149C8D232323000159002207
16:44:03.439 [pimatic-maxcul] debug: decoding Message Z0E010202149C8D232323000159002207
16:44:03.439 [pimatic-maxcul] debug: RSSI for Message : -70.5
16:44:03.442 [pimatic-maxcul] debug: got OK-ACK Packet from 149c8d
16:44:03.478 [pimatic-maxcul] debug: Send Packet to CUL: 0b01003042313116aa1e0012, awaiting drain event
16:44:03.500 [pimatic-maxcul] debug: serial port buffer have been drained
16:44:04.529 [pimatic-maxcul] debug: incoming raw data from CUL: Z0E01020216AA1E42313100011800091E
16:44:04.530 [pimatic-maxcul] debug: decoding Message Z0E01020216AA1E42313100011800091E
16:44:04.530 [pimatic-maxcul] debug: RSSI for Message : -59
16:44:04.531 [pimatic-maxcul] debug: got OK-ACK Packet from 16aa1e
16:44:04.532 [pimatic-maxcul] debug: no packet to handle in send queue
```
**Not working**
```
16:38:13.109 [pimatic] info: Loading plugin: "pimatic-maxcul" (1.1.0)
16:38:13.110 [pimatic] debug: debug is true in plugin config, showing debug output for pimatic-maxcul.
16:38:38.241 [pimatic-maxcul] info: using serial device /dev/cube@38400
16:38:38.626 [pimatic-maxcul] info: serialPort /dev/cube is open!
16:38:38.626 [pimatic-maxcul] debug: check CUL Firmware version
16:38:38.636 [pimatic-maxcul] debug: Requested CUL Version...
16:38:40.913 [pimatic-maxcul] debug: templates loaded
16:38:41.013 [pimatic-maxcul] debug: Send Packet to CUL: 0b010630232323149c8d2010, awaiting drain event
16:38:41.062 [pimatic-maxcul] debug: serial port buffer have been drained
16:38:42.702 [pimatic-maxcul] debug: incoming raw data from CUL: Z0E010202149C8D2323230001590022
16:38:42.702 [pimatic-maxcul] debug: decoding Message Z0E010202149C8D2323230001590022
16:38:42.703 [pimatic-maxcul] debug: RSSI for Message : -57
16:38:42.703 [pimatic-maxcul] debug: packet length missmatch
16:38:42.703 [pimatic-maxcul] debug: message was no valid MAX! paket.
16:38:43.461 [pimatic-maxcul] debug: incoming raw data from CUL: Z0F00046016A9D40000000019000B00E4
16:38:43.462 [pimatic-maxcul] debug: decoding Message Z0F00046016A9D40000000019000B00E4
16:38:43.462 [pimatic-maxcul] debug: RSSI for Message : -88
16:38:43.462 [pimatic-maxcul] debug: packet length missmatch
16:38:43.462 [pimatic-maxcul] debug: message was no valid MAX! paket.
16:38:43.904 [pimatic-maxcul] debug: Retransmit packet 0b010630232323149c8d2010, try 1 of 3
16:38:43.905 [pimatic-maxcul] debug: Send Packet to CUL: 0b010630232323149c8d2010, awaiting drain event
16:38:43.906 [pimatic-maxcul] debug: serial port buffer have been drained
16:38:44.989 [pimatic-maxcul] debug: incoming raw data from CUL: Z0E010202149C8D2323230001590022
16:38:44.990 [pimatic-maxcul] debug: decoding Message Z0E010202149C8D2323230001590022
16:38:44.990 [pimatic-maxcul] debug: RSSI for Message : -57
16:38:44.990 [pimatic-maxcul] debug: packet length missmatch
16:38:44.990 [pimatic-maxcul] debug: message was no valid MAX! paket.
16:38:46.905 [pimatic-maxcul] debug: Retransmit packet 0b010630232323149c8d2010, try 2 of 3
16:38:46.909 [pimatic-maxcul] debug: Send Packet to CUL: 0b010630232323149c8d2010, awaiting drain event
16:38:46.910 [pimatic-maxcul] debug: serial port buffer have been drained
16:38:47.993 [pimatic-maxcul] debug: incoming raw data from CUL: Z0E010202149C8D2323230001590022
16:38:47.996 [pimatic-maxcul] debug: decoding Message Z0E010202149C8D2323230001590022
16:38:47.997 [pimatic-maxcul] debug: RSSI for Message : -57
16:38:47.997 [pimatic-maxcul] debug: packet length missmatch
16:38:47.998 [pimatic-maxcul] debug: message was no valid MAX! paket.
16:38:49.906 [pimatic-maxcul] debug: Retransmit packet 0b010630232323149c8d2010, try 3 of 3
```

**Comment by fbeek** [comment] 2019-08-17 23:26
Hello Kosta, 
thank you for your data.
Iam this week on vacation but on the next weekend I will dig deeper Into this problem.
At the moment i think there is some problem with stretch and the new serial port version.

Best Regards
Flo

**Comment by treban** [comment] 2019-08-18 06:00
Hi Flo,
No stress. I am also on vacation next week and until winter is still time.
BR
Kosta

**Comment by fbeek** [comment] 2019-09-25 09:20
Hello Guys,

I want to let you know that I am Still working on this.
I had some problems with my development rig so i lost some time.

But I am on it now with a new pi 4 :-)

BG
Flo

**Comment by MaxWinterstein** [comment] 2019-10-08 18:24
Hi Flo,

keep up the good work - its getting cold here these days ;)

Same issue for me here, disabling debugging seems to work - at least for now. 

```
max@pimatic:~/pimatic-app-node8$ cat /etc/issue
Ubuntu 16.04.5 LTS \n \

max@pimatic:~/pimatic-app-node8$ head pimatic-daemon.log
23:24:16.294 2019-10-04 Friday
23:24:18.589 [pimatic] info: Starting pimatic version 0.9.53
23:24:18.593 [pimatic] info: Node.js version 10.16.3
```

**Comment by fbeek** [comment] 2019-10-12 18:34
Hello Together,

i give my best :-D

@MaxWinterstein: So the error is gone on your system if you disable the debugging mode of the plugin and are you using Ubuntu on an raspberry pi or on an normal system?

**Comment by MaxWinterstein** [comment] 2019-11-25 22:07
So, this still bugs me. 

Disable debugging mode does not lead the a big change for me.
At least sending temperatures seems to work, but also window sensors struggle badly to do their jobs...

I tried using Node.js 10.16.0 but that does not get my any further.

I switched to docker based pimatic as installing node versions was a huge pain...

So, any update on this, or combination that should work for sure?

greetings
max

**Comment by fbeek** [comment] 2019-12-06 18:51
I have merged the pull request from Kosta.

On my testing rig it fixed the problem, so please update to v1.1.1.

**Closed as completed by fbeek** 2019-12-06 18:51 UTC
Labels: in progress

**Comment by MaxWinterstein** [comment] 2019-12-07 22:53
Holy Moly, this works fine for me!

Thank you @treban  - i was nearly going to throw all that stuff out of the window! Next beer is on me :)

Gruß aus Frankfurt

**Comment by treban** [comment] 2019-12-08 20:06
You're welcome. Thx for the beer ;) But you shouldn't have.

**Comment by sleepinghead** [comment] 2020-01-09 19:38
Hello all,

I am running the same problem, the plugin checks the Firmware Version but does not get any response from the nanocul. If I use "cutecom-ng" on my Macbook I get response by sending "V".

Looking for help. THX

**system**
aspberry pi 3
pimatic version 0.9.54
Node.js version 8.11.1
OpenSSL version 1.0.2l
pimatic-maxcul 1.1.1
hardware: nanoV3 with CC1101 868
Firmware: I tried 1.26.07 and 1.6.7 from a-culfw 

**Config.json**
>{
      "plugin": "maxcul",
      "serialPortName": "/dev/serial/by-path/platform-3f980000.usb-usb-0:1.1.3:1.0-port0",
      "homebaseAddress": "123456",
      "baudrate": 38400,
      "debug": true
}
    

 

**Log**
20:32:21.584 [pimatic] Starting pimatic version 0.9.54
20:32:21.592 [pimatic] Node.js version 8.11.1
20:32:21.593 [pimatic] OpenSSL version 1.0.2l
20:32:21.722 [pimatic] settings.debug is true, showing debug output for pimatic core.
20:32:24.992 [pimatic, ppm] 2.15.12
20:32:25.029 [pimatic] Loading plugin: "pimatic-cron" (0.8.8)
20:32:25.468 [pimatic] Loading plugin: "pimatic-mobile-frontend" (0.9.16)
20:32:26.126 [pimatic] Loading plugin: "pimatic-maxcul" (1.1.1)
20:32:26.128 [pimatic] debug is true in plugin config, showing debug output for pimatic-maxcul.
20:32:26.322 [pimatic-cron] the time is: Thu Jan 09 2020 20:32:26 GMT+0100 (CET)
20:32:26.334 [pimatic-maxcul] using serial device /dev/serial/by-path/platform-3f980000.usb-usb-0:1.1.3:1.0-port0@38400
20:32:26.707 [pimatic-maxcul] templates loaded
20:32:26.925 [pimatic-maxcul] serialPort /dev/serial/by-path/platform-3f980000.usb-usb-0:1.1.3:1.0-port0 is open!
20:32:26.928 [pimatic-maxcul] check CUL Firmware version
20:32:27.052 [pimatic-mobile-frontend] packing static assets
20:32:27.830 [pimatic-mobile-frontend] packing static assets finished
20:32:27.837 [pimatic-mobile-frontend] rendering html
20:32:33.059 [pimatic-mobile-frontend] rendering html finished
20:32:33.092 [pimatic] Listening for HTTP-request on port 88...
20:32:33.103 [pimatic-maxcul] Requested CUL Version...
